version: '3.8'

services:
  postgres_users:
    image: postgres:latest
    container_name: "postgres_users"
    env_file: .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5632:5432"
    volumes:
      - ./conf/postgres_users/shards.sql:/docker-entrypoint-initdb.d/start.sql

  postgres_users1:
    image: postgres:latest
    container_name: "postgres_users1"
    env_file: .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5633:5432"
    volumes:
      - ./conf/postgres_users1/shards.sql:/docker-entrypoint-initdb.d/start.sql

  postgres_users2:
    image: postgres:latest
    container_name: "postgres_users2"
    env_file: .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5634:5432"
    volumes:
      - ./conf/postgres_users2/shards.sql:/docker-entrypoint-initdb.d/start.sql

