version: '3.8'

services:
  users_db:
    image: postgres:latest
    container_name: "users_db"
    env_file: .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5632:5432"
    volumes:
      - ./conf/users_db/shards.sql:/docker-entrypoint-initdb.d/start.sql

  users_shard1:
    image: postgres:latest
    container_name: "users_shard1"
    env_file: .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5633:5432"
    volumes:
      - ./conf/users_shard1/shards.sql:/docker-entrypoint-initdb.d/start.sql
    depends_on:
      - users_db

  users_shard2:
    image: postgres:latest
    container_name: "users_shard2"
    env_file: .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5634:5432"
    volumes:
      - ./conf/users_shard2/shards.sql:/docker-entrypoint-initdb.d/start.sql
    depends_on:
      - users_db
